
name: build on macos, ubuntu, windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    name: build and run on macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: build project
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: run with static linking
      run: ./build/homework/01-hello-world/hello-world-static
    - name: run with shared linking
      run: ./build/homework/01-hello-world/hello-world-shared
  
  build-ubuntu:
    name: build and run on ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build project
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: run with static linking
      run: ./build/homework/01-hello-world/hello-world-static
    - name: run with shared linking
      run: ./build/homework/01-hello-world/hello-world-shared

  build-windows:
    name: build and run on windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    
    - name: build project
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cmake -S . -B build/
        cmake --build build/
    - name: run with static linking
      run: build\homework\01-hello-world\Debug\hello-world-static.exe
    - name: run with shared linking
      run: build\Debug\hello-world-shared.exe
